#### Preprocessing of the merged file.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("all_participant_merged.csv")
df.columns

C:\Users\dynabook\AppData\Local\Temp\ipykernel_26496\2152941299.py:1: DtypeWarning: Columns (12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("all_participant_merged.csv")

Index(['source_file', 'Respondent Gender', 'Respondent Group', 'Row',
       'Timestamp', 'EventSource', 'SlideEvent', 'StimType', 'Duration',
       'CollectionPhase', 'SourceStimuliName', 'EventSource.1',
       'InputEventSource', 'Data', 'StimType.1', 'EventSource.2',
       'ET_GazeLeftx', 'ET_GazeLefty', 'ET_GazeRightx', 'ET_GazeRighty',
       'ET_PupilLeft', 'ET_PupilRight', 'ET_TimeSignal', 'ET_DistanceLeft',
       'ET_DistanceRight', 'ET_CameraLeftX', 'ET_CameraLeftY',
       'ET_CameraRightX', 'ET_CameraRightY', 'ET_ValidityLeft',
       'ET_ValidityRight', 'EventSource.3', 'Gaze X', 'Gaze Y',
       'Interpolated Gaze X', 'Interpolated Gaze Y', 'Interpolated Distance',
       'Gaze Velocity', 'Gaze Acceleration', 'Fixation Index',
       'Fixation Index by Stimulus', 'Fixation X', 'Fixation Y',
       'Fixation Start', 'Fixation End', 'Fixation Duration',
       'Fixation Dispersion', 'Saccade Index', 'Saccade Index by Stimulus',
       'Saccade Start', 'Saccade End', 'Saccade Duration', 'Saccade Amplitude',
       'Saccade Peak Velocity', 'Saccade Peak Acceleration',
       'Saccade Peak Deceleration', 'Saccade Direction'],
      dtype='object')

In [3]:
df.head(20)

,source_file,Respondent Gender,Respondent Group,Row,Timestamp,EventSource,SlideEvent,StimType,Duration,CollectionPhase,...,Saccade Index,Saccade Index by Stimulus,Saccade Start,Saccade End,Saccade Duration,Saccade Amplitude,Saccade Peak Velocity,Saccade Peak Acceleration,Saccade Peak Deceleration,Saccade Direction
0,001_Med_2_Zain_Burney.csv,MALE,Med 2,1,19721.3268,1.0,StartSlide,TestImage,30000.0,StimuliDisplay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,001_Med_2_Zain_Burney.csv,MALE,Med 2,2,19732.0258,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,001_Med_2_Zain_Burney.csv,MALE,Med 2,3,19748.2431,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,001_Med_2_Zain_Burney.csv,MALE,Med 2,4,19765.2603,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,001_Med_2_Zain_Burney.csv,MALE,Med 2,5,19781.0783,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,001_Med_2_Zain_Burney.csv,MALE,Med 2,6,19798.4496,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,001_Med_2_Zain_Burney.csv,MALE,Med 2,7,19814.5720,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,001_Med_2_Zain_Burney.csv,MALE,Med 2,8,19831.2949,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,001_Med_2_Zain_Burney.csv,MALE,Med 2,9,19848.6633,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,001_Med_2_Zain_Burney.csv,MALE,Med 2,10,19865.0355,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,001_Med_2_Zain_Burney.csv,MALE,Med 2,11,19882.0206,NaN,NaN,NaN,NaN,NaN,...,161.0,NaN,19873.52805,19922.93450,49.40645,11.764115,353.318968,12379.435596,-14421.718924,189.633661
11,001_Med_2_Zain_Burney.csv,MALE,Med 2,12,19897.8010,NaN,NaN,NaN,NaN,NaN,...,161.0,NaN,19873.52805,19922.93450,49.40645,11.764115,353.318968,12379.435596,-14421.718924,189.633661
12,001_Med_2_Zain_Burney.csv,MALE,Med 2,13,19914.4865,NaN,NaN,NaN,NaN,NaN,...,161.0,NaN,19873.52805,19922.93450,49.40645,11.764115,353.318968,12379.435596,-14421.718924,189.633661
13,001_Med_2_Zain_Burney.csv,MALE,Med 2,14,19916.0802,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,001_Med_2_Zain_Burney.csv,MALE,Med 2,15,19926.0740,1.0,StartMedia,TestImage,30000.0,StimuliDisplay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,001_Med_2_Zain_Burney.csv,MALE,Med 2,16,19931.3825,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,001_Med_2_Zain_Burney.csv,MALE,Med 2,17,19947.9262,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,001_Med_2_Zain_Burney.csv,MALE,Med 2,18,19964.5442,NaN,NaN,NaN,NaN,NaN,...,162.0,1.0,19956.23520,19973.02705,16.79185,NaN,37.759480,926.070300,NaN,NaN
18,001_Med_2_Zain_Burney.csv,MALE,Med 2,19,19981.5099,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,001_Med_2_Zain_Burney.csv,MALE,Med 2,20,19998.2886,NaN,NaN,NaN,NaN,NaN,...,163.0,2.0,19989.89925,20006.62050,16.72125,NaN,49.787738,1777.984987,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1036714 entries, 0 to 1036713
Data columns (total 57 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   source_file                 1036714 non-null  object
 1   Respondent Gender           1018539 non-null  object
 2   Respondent Group            1018539 non-null  object
 3   Row                         1036714 non-null  int64
 4   Timestamp                   1036714 non-null  float64
 5   EventSource                 2520 non-null     float64
 6   SlideEvent                  2520 non-null     object
 7   StimType                    2520 non-null     object
 8   Duration                    2520 non-null     float64
 9   CollectionPhase             2520 non-null     object
 10  SourceStimuliName           1036714 non-null  object
 11  EventSource.1               28090 non-null    float64
 12  InputEventSource            28090 non-null    object
 13  Data                        28090 non-null    object
 14  StimType.1                  28090 non-null    object
 15  EventSource.2               1006239 non-null  float64
 16  ET_GazeLeftx                1006239 non-null  float64
 17  ET_GazeLefty                1006239 non-null  float64
 18  ET_GazeRightx               1006239 non-null  float64
 19  ET_GazeRighty               1006239 non-null  float64
 20  ET_PupilLeft                1006239 non-null  float64
 21  ET_PupilRight               1006239 non-null  float64
 22  ET_TimeSignal               1006239 non-null  float64
 23  ET_DistanceLeft             1006239 non-null  float64
 24  ET_DistanceRight            1006239 non-null  float64
 25  ET_CameraLeftX              1006239 non-null  float64
 26  ET_CameraLeftY              1006239 non-null  float64
 27  ET_CameraRightX             1006239 non-null  float64
 28  ET_CameraRightY             1006239 non-null  float64
 29  ET_ValidityLeft             1006239 non-null  float64
 30  ET_ValidityRight            1006239 non-null  float64
 31  EventSource.3               1006239 non-null  float64
 32  Gaze X                      909989 non-null   float64
 33  Gaze Y                      898203 non-null   float64
 34  Interpolated Gaze X         909989 non-null   float64
 35  Interpolated Gaze Y         898203 non-null   float64
 36  Interpolated Distance       913977 non-null   float64
 37  Gaze Velocity               860687 non-null   float64
 38  Gaze Acceleration           849339 non-null   float64
 39  Fixation Index              427271 non-null   float64
 40  Fixation Index by Stimulus  422317 non-null   float64
 41  Fixation X                  427271 non-null   float64
 42  Fixation Y                  427271 non-null   float64
 43  Fixation Start              427271 non-null   float64
 44  Fixation End                427271 non-null   float64
 45  Fixation Duration           427271 non-null   float64
 46  Fixation Dispersion         349383 non-null   float64
 47  Saccade Index               433416 non-null   float64
 48  Saccade Index by Stimulus   430297 non-null   float64
 49  Saccade Start               433416 non-null   float64
 50  Saccade End                 433416 non-null   float64
 51  Saccade Duration            433416 non-null   float64
 52  Saccade Amplitude           360054 non-null   float64
 53  Saccade Peak Velocity       433416 non-null   float64
 54  Saccade Peak Acceleration   427486 non-null   float64
 55  Saccade Peak Deceleration   326365 non-null   float64
 56  Saccade Direction           360054 non-null   float64
dtypes: float64(46), int64(1), object(10)
memory usage: 450.8+ MB

In [5]:
df['Data'].unique()

array([nan, 'Id:M;X:683;Y:384', 'Id:M;X:683;Y:385', ...,
       'Id:M;X:653;Y:362', 'Id:M;X:656;Y:366', 'Id:M;X:656;Y:367'],
      dtype=object)

In [6]:
df[['Fixation End','Fixation Start']]

         Fixation End  Fixation Start
0                 NaN             NaN
1         19873.52805      19640.1956
2         19873.52805      19640.1956
3         19873.52805      19640.1956
4         19873.52805      19640.1956
...               ...             ...
1036709  408058.10505     408008.1725
1036710  408058.10505     408008.1725
1036711           NaN             NaN
1036712           NaN             NaN
1036713           NaN             NaN

[1036714 rows x 2 columns]

In [7]:
df[['Fixation X', 'Fixation Y']].describe()

          Fixation X     Fixation Y
count  427271.000000  427271.000000
mean      553.688916     342.371365
std       310.457580     198.364634
min         0.000000       0.000000
25%       273.388889     177.000000
50%       539.000000     313.166667
75%       790.725000     497.000000
max      1364.000000     768.000000

In [8]:
df.columns

Index(['source_file', 'Respondent Gender', 'Respondent Group', 'Row',
       'Timestamp', 'EventSource', 'SlideEvent', 'StimType', 'Duration',
       'CollectionPhase', 'SourceStimuliName', 'EventSource.1',
       'InputEventSource', 'Data', 'StimType.1', 'EventSource.2',
       'ET_GazeLeftx', 'ET_GazeLefty', 'ET_GazeRightx', 'ET_GazeRighty',
       'ET_PupilLeft', 'ET_PupilRight', 'ET_TimeSignal', 'ET_DistanceLeft',
       'ET_DistanceRight', 'ET_CameraLeftX', 'ET_CameraLeftY',
       'ET_CameraRightX', 'ET_CameraRightY', 'ET_ValidityLeft',
       'ET_ValidityRight', 'EventSource.3', 'Gaze X', 'Gaze Y',
       'Interpolated Gaze X', 'Interpolated Gaze Y', 'Interpolated Distance',
       'Gaze Velocity', 'Gaze Acceleration', 'Fixation Index',
       'Fixation Index by Stimulus', 'Fixation X', 'Fixation Y',
       'Fixation Start', 'Fixation End', 'Fixation Duration',
       'Fixation Dispersion', 'Saccade Index', 'Saccade Index by Stimulus',
       'Saccade Start', 'Saccade End', 'Saccade Duration', 'Saccade Amplitude',
       'Saccade Peak Velocity', 'Saccade Peak Acceleration',
       'Saccade Peak Deceleration', 'Saccade Direction'],
      dtype='object')

In [ ]:
df_fixations = df[["Timestamp", "Duration","Fixation Duration", "Fixation X", "Fixation Y", "Data", "InputEventSource", "Fixation Start", "Fixation End", 'SourceStimuliName',"Timestamp","source_file"]]

KeyError: "['SourceStimulusName'] not in index"